CREATE TABLE USER_DETAILS 
(
      ZIP VARCHAR ,
      LAST_NAME VARCHAR ,
      USERNAME VARCHAR ,
      PHONE VARCHAR ,
      ADDRESS VARCHAR ,
      EMAIL VARCHAR ,
      USER_ID VARCHAR  NOT NULL,
      FIRST_NAME VARCHAR ,
      PASSWORD VARCHAR ,
      CITY VARCHAR ,
    CONSTRAINT USER_DETAILS_PK PRIMARY KEY(USER_ID)
);

CREATE TABLE SHIPMENT_LABEL 
(
      FROM_ADDR1 VARCHAR ,
      FROM_SENDER_EMAIL VARCHAR ,
      FROM_ADDR2 VARCHAR ,
      TO_SENDER_PHONE VARCHAR ,
      TO_ADDR1 VARCHAR ,
      FROM_CITY VARCHAR ,
      TO_ZIP VARCHAR ,
      TO_CITY VARCHAR ,
      TO_ADDR2 VARCHAR ,
      FROM_SENDER_NAME VARCHAR ,
      FROM_ZIP VARCHAR ,
      FROM_SENDER_PHONE VARCHAR ,
      FROM_COUNTRY VARCHAR ,
      TO_SENDER_EMAIL VARCHAR ,
      TO_COUNTRY VARCHAR ,
      SHIPMENT_ID NUMERIC  NOT NULL,
      CLIENT_ID NUMERIC  NOT NULL,
      TO_SENDER_NAME VARCHAR ,
    CONSTRAINT SHIPMENT_LABEL_PK PRIMARY KEY(SHIPMENT_ID,CLIENT_ID)
);

CREATE TABLE DATA_SYNCH_ACTIONS 
(
      ID NUMERIC NOT NULL,
      SERVICE_CLASS_NAME VARCHAR NOT NULL,
      ENTITY_CLASS_NAME VARCHAR NOT NULL,
      JSON_PAYLOAD VARCHAR ,
      ACTION VARCHAR NOT NULL,
      DATE_CREATED DATE NOT NULL,
      DATE_LAST_SYNCH DATE NOT NULL,
      LAST_SYNCH_ERROR VARCHAR,
      CUSTOM_METHOD_NAME VARCHAR,
    CONSTRAINT DSA_PK PRIMARY KEY(SERVICE_CLASS_NAME ,ID)
);

CREATE TABLE WEB_SERVICE_CALL 
(
      ID NUMERIC  NOT NULL,
      CONNECTION VARCHAR ,
      REQUEST VARCHAR ,
      METHOD VARCHAR ,
      REQUEST_HEADERS VARCHAR ,
      DURATION NUMERIC ,
      REQUEST_PAYLOAD VARCHAR ,
      RESPONSE_PAYLOAD VARCHAR ,
      ERROR_MESSAGE VARCHAR ,
      TIMESTAMP DATE ,
    CONSTRAINT WEB_SERVICE_CALL_PK PRIMARY KEY(ID)
);
